//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductStoreAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> AddedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual tbl_Category tbl_Category { get; set; }
        public virtual tbl_Currency tbl_Currency { get; set; }
        public virtual tbl_Unit tbl_Unit { get; set; }
    }
}
